# Generated by Django 5.1.3 on 2024-11-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trash_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='message',
        ),
    ]
