# Generated by Django 5.1.3 on 2024-11-16 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_app', '0002_remove_bid_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='trash_can',
        ),
        migrations.AddField(
            model_name='bid',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='image',
            field=models.ImageField(default='trash_project/media/trash_cans/133500.jpg', upload_to='trash_cans/'),
        ),
        migrations.AddField(
            model_name='bid',
            name='type',
            field=models.CharField(choices=[('trash', 'Свалка'), ('dirt', 'Не убрано')], default='safasda', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('pending', 'Рассматривается'), ('completed', 'Выполнено'), ('declined', 'Отклонено')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='trashcan',
            name='image',
            field=models.ImageField(default='trash_project/media/trash_cans/133500.jpg', upload_to='trash_cans/'),
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Выполнено'), ('declined', 'Отклонено')], default='in_progress', max_length=20)),
                ('image_before', models.ImageField(upload_to='tasks/before/')),
                ('image_after', models.ImageField(upload_to='tasks/after/')),
                ('location_before', models.CharField(blank=True, max_length=255, null=True)),
                ('location_after', models.CharField(blank=True, max_length=255, null=True)),
                ('datetime_before', models.DateTimeField(blank=True)),
                ('datetime_after', models.DateTimeField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='trash_app.bid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
