# Generated by Django 5.1.3 on 2024-11-16 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trash_app', '0005_alter_bid_user_alter_worker_user_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='address',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='phone_number',
        ),
    ]
