# Generated by Django 5.1.3 on 2024-11-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_app', '0006_remove_worker_address_remove_worker_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='user',
        ),
        migrations.AddField(
            model_name='bid',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
