# Generated by Django 5.1.3 on 2024-11-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_app', '0007_remove_bid_user_bid_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bids', models.IntegerField(default=0)),
                ('resolved_bids', models.IntegerField(default=0)),
                ('active_bids', models.IntegerField(default=0)),
                ('average_reaction_time', models.DurationField(blank=True, null=True)),
                ('average_completion_time', models.DurationField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='address',
            new_name='coordinates',
        ),
    ]
