# Generated by Django 5.1.3 on 2024-11-17 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_app', '0008_analytics_rename_address_bid_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='chat_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(choices=[('check_by_human', 'Требуется ручная проверка'), ('check_by_ai', 'Обработаны ИИ'), ('no_trash_cans', 'На фото нет баков')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='trash_app.bid')),
            ],
        ),
    ]
